eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9002
spring:
  application:
    name: rating-service
